### ISSUE TITLE
Installing OpenSRS fails with "README.md: No such file or directory"

### ISSUE THREAD

**Issue by sergeyv** [fatbox/OpenSRS-py#1]
OpenSRS 0.1.1 tarball on pypi does not include README.md so installing the egg fails because setup.py tries to open that file.

You need to add MANIFEST.in file which will tell distutils to include README.md into the source tarball:

http://docs.python.org/distutils/sourcedist.html#the-manifest-in-template

**Comment by fatbox** [comment]
Thanks for the bug report. This has been fixed and pushed up to pypi.
